import type React from "react";
import type { Stock } from "@/types";

export const STOCKS: Stock[] = [
  {
    ticker: "005930.KS",
    name: "삼성전자",
    sector: "반도체 / AI",
    sectorColor: "blue",
    description: "메모리 반도체와 AI 수요를 중심으로 한국 증시를 대표하는 기업입니다.",
  },
  {
    ticker: "000660.KS",
    name: "SK하이닉스",
    sector: "반도체 / AI",
    sectorColor: "blue",
    description: "HBM과 메모리 반도체를 중심으로 AI 인프라 수요와 연결된 기업입니다.",
  },
  {
    ticker: "042700.KS",
    name: "한미반도체",
    sector: "반도체 / AI",
    sectorColor: "blue",
    description: "반도체 후공정 장비를 다루며 AI 반도체 공급망과 연결되는 기업입니다.",
  },
  {
    ticker: "267260.KS",
    name: "HD현대일렉트릭",
    sector: "전력기기 / AI 인프라",
    sectorColor: "amber",
    description: "전력기기와 변압기 사업을 통해 데이터센터 전력 수요와 연결되는 기업입니다.",
  },
  {
    ticker: "010120.KS",
    name: "LS ELECTRIC",
    sector: "전력기기 / AI 인프라",
    sectorColor: "amber",
    description: "전력 자동화와 스마트그리드 사업을 다루는 전력 인프라 기업입니다.",
  },
  {
    ticker: "298040.KS",
    name: "효성중공업",
    sector: "전력기기 / AI 인프라",
    sectorColor: "amber",
    description: "변압기와 전력 설비를 중심으로 글로벌 전력 인프라 흐름과 연결되는 기업입니다.",
  },
  {
    ticker: "329180.KS",
    name: "HD현대중공업",
    sector: "조선",
    sectorColor: "purple",
    description: "대형 선박과 해양 플랜트를 건조하는 국내 대표 조선 기업입니다.",
  },
  {
    ticker: "042660.KS",
    name: "한화오션",
    sector: "조선",
    sectorColor: "purple",
    description: "선박과 해양 사업을 중심으로 조선 산업 흐름을 보여주는 기업입니다.",
  },
  {
    ticker: "010140.KS",
    name: "삼성중공업",
    sector: "조선",
    sectorColor: "purple",
    description: "LNG선과 해양 플랜트 등 고부가 선박 중심의 조선 기업입니다.",
  },
  {
    ticker: "012450.KS",
    name: "한화에어로스페이스",
    sector: "항공우주",
    sectorColor: "red",
    description: "항공우주와 정밀기계 산업 흐름을 보여주는 대표 기업입니다.",
  },
  {
    ticker: "047810.KS",
    name: "한국항공우주",
    sector: "항공우주",
    sectorColor: "red",
    description: "항공기 개발과 항공우주 산업을 중심으로 성장하는 기업입니다.",
  },
  {
    ticker: "064350.KS",
    name: "현대로템",
    sector: "산업 / 모빌리티",
    sectorColor: "red",
    description: "철도 차량과 산업 시스템을 통해 모빌리티 인프라 흐름을 보여주는 기업입니다.",
  },
  {
    ticker: "034020.KS",
    name: "두산에너빌리티",
    sector: "원전 / 에너지",
    sectorColor: "amber",
    description: "발전 설비와 에너지 인프라 사업을 다루는 대표 에너지 기업입니다.",
  },
  {
    ticker: "015760.KS",
    name: "한국전력",
    sector: "원전 / 에너지",
    sectorColor: "amber",
    description: "국내 전력 공급과 에너지 정책 흐름을 보여주는 대표 전력 공기업입니다.",
  },
  {
    ticker: "000720.KS",
    name: "현대건설",
    sector: "원전 / 에너지",
    sectorColor: "amber",
    description: "건설과 인프라 사업을 통해 에너지 및 사회 기반 시설 흐름과 연결되는 기업입니다.",
  },
  {
    ticker: "373220.KS",
    name: "LG에너지솔루션",
    sector: "2차전지",
    sectorColor: "green",
    description: "전기차 배터리와 에너지 저장장치를 중심으로 2차전지 산업을 대표하는 기업입니다.",
  },
  {
    ticker: "006400.KS",
    name: "삼성SDI",
    sector: "2차전지",
    sectorColor: "green",
    description: "전기차 배터리와 전자재료 사업을 기반으로 성장하는 2차전지 기업입니다.",
  },
  {
    ticker: "005490.KS",
    name: "POSCO홀딩스",
    sector: "2차전지",
    sectorColor: "green",
    description: "철강을 기반으로 리튬과 2차전지 소재 사업까지 확장하는 소재 대표 기업입니다.",
  },
  {
    ticker: "005380.KS",
    name: "현대차",
    sector: "자동차 / 미래차",
    sectorColor: "red",
    description: "내연기관차, 전기차, 수소차 전환을 추진하는 국내 대표 완성차 기업입니다.",
  },
  {
    ticker: "000270.KS",
    name: "기아",
    sector: "자동차 / 미래차",
    sectorColor: "red",
    description: "글로벌 완성차 판매와 전기차 라인업 확대를 통해 자동차 시장 흐름을 보여주는 기업입니다.",
  },
  {
    ticker: "012330.KS",
    name: "현대모비스",
    sector: "자동차 / 미래차",
    sectorColor: "red",
    description: "자동차 부품과 전장 사업을 중심으로 미래차 전환과 연결되는 기업입니다.",
  },
  {
    ticker: "207940.KS",
    name: "삼성바이오로직스",
    sector: "바이오 / 헬스케어",
    sectorColor: "purple",
    description: "바이오 의약품 위탁개발생산을 중심으로 성장하는 국내 대표 바이오 기업입니다.",
  },
  {
    ticker: "068270.KS",
    name: "셀트리온",
    sector: "바이오 / 헬스케어",
    sectorColor: "purple",
    description: "바이오시밀러와 의약품 개발, 글로벌 판매를 중심으로 성장하는 바이오 기업입니다.",
  },
  {
    ticker: "000100.KS",
    name: "유한양행",
    sector: "바이오 / 헬스케어",
    sectorColor: "purple",
    description: "신약 개발과 제약 사업을 기반으로 국내 제약 산업의 흐름을 보여주는 기업입니다.",
  },
  {
    ticker: "105560.KS",
    name: "KB금융",
    sector: "금융",
    sectorColor: "blue",
    description: "은행, 증권, 보험 등 금융 서비스를 제공하는 국내 대표 금융지주입니다.",
  },
  {
    ticker: "055550.KS",
    name: "신한지주",
    sector: "금융",
    sectorColor: "blue",
    description: "은행과 카드, 증권 등 다양한 금융 계열사를 보유한 금융지주 기업입니다.",
  },
  {
    ticker: "086790.KS",
    name: "하나금융지주",
    sector: "금융",
    sectorColor: "blue",
    description: "하나은행을 중심으로 은행, 증권, 카드 등 금융 서비스를 제공하는 금융지주입니다.",
  },
  {
    ticker: "035420.KS",
    name: "NAVER",
    sector: "플랫폼 / 게임",
    sectorColor: "green",
    description: "검색, 커머스, 콘텐츠, 클라우드와 AI 서비스를 운영하는 플랫폼 기업입니다.",
  },
  {
    ticker: "035720.KS",
    name: "카카오",
    sector: "플랫폼 / 게임",
    sectorColor: "green",
    description: "메신저, 콘텐츠, 페이, 모빌리티 등 생활 밀착형 플랫폼 서비스를 운영합니다.",
  },
  {
    ticker: "259960.KS",
    name: "크래프톤",
    sector: "플랫폼 / 게임",
    sectorColor: "green",
    description: "게임과 글로벌 콘텐츠 사업을 중심으로 디지털 콘텐츠 산업 흐름을 보여주는 기업입니다.",
  },
];

export function getStock(ticker: string): Stock | undefined {
  return STOCKS.find((stock) => stock.ticker === ticker);
}

export const SECTOR_BADGE_STYLES: Record<Stock["sectorColor"], React.CSSProperties> = {
  blue: { background: "#dbeafe", color: "#1d4ed8" },
  green: { background: "#d1fae5", color: "#065f46" },
  amber: { background: "#fef3c7", color: "#92400e" },
  purple: { background: "#ede9fe", color: "#6d28d9" },
  red: { background: "#fee2e2", color: "#b91c1c" },
};
